#!/usr/bin/env python3
"""
QJL Stage 2 Accuracy Curve Plotter
====================================
Reads `results/qjl_results.json` (generated by `cargo run --example full_pipeline --release`)
and produces a 3-panel figure saved as `results/qjl_accuracy.png`.

Usage:
    cargo run --example full_pipeline --release
    python3 scripts/plot_qjl_accuracy.py

Requires:
    pip install matplotlib numpy
"""

import json
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.gridspec import GridSpec

# ── Load data ─────────────────────────────────────────────────────────────────

JSON_PATH  = "results/qjl_results.json"
OUTPUT_PNG = "results/qjl_accuracy.png"

if not os.path.exists(JSON_PATH):
    print(f"Error: {JSON_PATH} not found.")
    print("Run:  cargo run --example full_pipeline --release")
    sys.exit(1)

with open(JSON_PATH) as f:
    data = json.load(f)

results   = data["qjl_results"]
sk_dims   = [r["sketch_dim"]               for r in results]
ip_errors = [r["mean_abs_ip_error"]        for r in results]
top16     = [r["top16_attention_overlap"]  for r in results]
overheads = [r["memory_overhead_fraction"] * 100 for r in results]
total_bytes = [r["total_bytes"]            for r in results]

# ── Style ──────────────────────────────────────────────────────────────────────

ACCENT_RED   = "#e05c5c"
ACCENT_GREEN = "#4caf50"
ACCENT_BLUE  = "#4a9eff"
BG           = "#0f1117"
CARD         = "#1a1d27"
TEXT         = "#e8eaf0"
GRID         = "#2a2d3a"

plt.rcParams.update({
    "figure.facecolor":  BG,
    "axes.facecolor":    CARD,
    "axes.edgecolor":    GRID,
    "axes.labelcolor":   TEXT,
    "text.color":        TEXT,
    "xtick.color":       TEXT,
    "ytick.color":       TEXT,
    "grid.color":        GRID,
    "grid.alpha":        0.6,
    "font.family":       "DejaVu Sans",
    "font.size":         11,
    "axes.titlesize":    13,
    "axes.titleweight":  "bold",
})

# ── Figure layout ──────────────────────────────────────────────────────────────

fig = plt.figure(figsize=(16, 6), facecolor=BG)
fig.suptitle(
    "TurboQuant Stage 2 — QJL Residual Sketch: Accuracy vs Memory Tradeoff",
    fontsize=16, fontweight="bold", color=TEXT, y=1.02
)

gs = GridSpec(1, 3, figure=fig, wspace=0.35)
ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1])
ax3 = fig.add_subplot(gs[2])

marker_kw = dict(linewidth=2.5, markersize=9, markeredgewidth=1.5, markeredgecolor="white")

# ── Panel 1: Inner Product Error vs k ────────────────────────────────────────

ax1.plot(sk_dims, ip_errors, "o-", color=ACCENT_RED, **marker_kw)
ax1.fill_between(sk_dims, ip_errors, alpha=0.15, color=ACCENT_RED)
for x, y in zip(sk_dims, ip_errors):
    ax1.annotate(f"{y:.4f}", (x, y), textcoords="offset points",
                 xytext=(0, 10), ha="center", fontsize=9, color=ACCENT_RED)

ax1.set_xlabel("Sketch Dimension k", labelpad=8)
ax1.set_ylabel("Mean |Inner Product Error|", labelpad=8)
ax1.set_title("IP Error vs Sketch Size")
ax1.set_xscale("log", base=2)
ax1.xaxis.set_major_formatter(mticker.ScalarFormatter())
ax1.grid(True, linestyle="--")
ax1.set_xticks(sk_dims)

# ── Panel 2: Top-16 Attention Overlap vs k ────────────────────────────────────

ax2.plot(sk_dims, [v * 100 for v in top16], "s-", color=ACCENT_GREEN, **marker_kw)
ax2.fill_between(sk_dims, [v * 100 for v in top16], alpha=0.15, color=ACCENT_GREEN)
ax2.axhline(y=85, color=ACCENT_GREEN, linestyle=":", linewidth=1.5, alpha=0.6,
            label="85% threshold")
for x, y in zip(sk_dims, [v * 100 for v in top16]):
    ax2.annotate(f"{y:.1f}%", (x, y), textcoords="offset points",
                 xytext=(0, -18), ha="center", fontsize=9, color=ACCENT_GREEN)

ax2.set_xlabel("Sketch Dimension k", labelpad=8)
ax2.set_ylabel("Top-16 Attention Overlap (%)", labelpad=8)
ax2.set_title("Attention Rank Preservation vs k")
ax2.set_xscale("log", base=2)
ax2.xaxis.set_major_formatter(mticker.ScalarFormatter())
ax2.set_ylim([0, 108])
ax2.legend(fontsize=9, loc="lower right")
ax2.grid(True, linestyle="--")
ax2.set_xticks(sk_dims)

# ── Panel 3: Quality vs Memory Overhead ───────────────────────────────────────

ax3.plot(overheads, [v * 100 for v in top16], "D-", color=ACCENT_BLUE, **marker_kw)
for x, y, k in zip(overheads, [v * 100 for v in top16], sk_dims):
    ax3.annotate(f"k={k}", (x, y), textcoords="offset points",
                 xytext=(8, 4), ha="left", fontsize=9, color=ACCENT_BLUE)

fp16_bytes = 512 * 2
ax3_top = ax3.twiny()
ax3_top.set_xlim(ax3.get_xlim())

ax3.set_xlabel("Memory Overhead vs FP16 (%)", labelpad=8)
ax3.set_ylabel("Top-16 Attention Overlap (%)", labelpad=8)
ax3.set_title("Quality vs Memory Tradeoff")
ax3.set_ylim([0, 108])
ax3.grid(True, linestyle="--")
ax3_top.set_xlabel("Total bytes at d=512", labelpad=6)
ax3_top.set_xticks(overheads)
ax3_top.set_xticklabels([str(b) for b in total_bytes], fontsize=8)

# ── Subtitle annotation ───────────────────────────────────────────────────────

fig.text(
    0.5, -0.06,
    "d=512, 5,000 random unit vectors · PolarQ-3bit + QJL sketch · "
    "Based on TurboQuant (arXiv:2504.19874)",
    ha="center", va="top", fontsize=9, color="#888899"
)

# ── Save ──────────────────────────────────────────────────────────────────────

os.makedirs("results", exist_ok=True)
plt.tight_layout()
plt.savefig(OUTPUT_PNG, dpi=150, bbox_inches="tight", facecolor=BG)
print(f"\u2713 Saved: {OUTPUT_PNG}")

# Also save individual panels for LinkedIn
for i, (ax, name) in enumerate([(ax1, "ip_error"), (ax2, "top16_overlap"), (ax3, "qvmem_tradeoff")]):
    fig_solo, ax_solo = plt.subplots(figsize=(6, 5), facecolor=BG)
    ax_solo.set_facecolor(CARD)
    # Redraw each panel individually
    if i == 0:
        ax_solo.plot(sk_dims, ip_errors, "o-", color=ACCENT_RED, **marker_kw)
        ax_solo.fill_between(sk_dims, ip_errors, alpha=0.15, color=ACCENT_RED)
        ax_solo.set_xlabel("Sketch Dimension k"); ax_solo.set_ylabel("Mean |IP Error|")
        ax_solo.set_title("IP Error vs Sketch Size"); ax_solo.set_xscale("log", base=2)
        ax_solo.xaxis.set_major_formatter(mticker.ScalarFormatter())
        ax_solo.set_xticks(sk_dims); ax_solo.grid(True, linestyle="--")
    elif i == 1:
        ax_solo.plot(sk_dims, [v * 100 for v in top16], "s-", color=ACCENT_GREEN, **marker_kw)
        ax_solo.fill_between(sk_dims, [v * 100 for v in top16], alpha=0.15, color=ACCENT_GREEN)
        ax_solo.axhline(y=85, color=ACCENT_GREEN, linestyle=":", linewidth=1.5, alpha=0.6)
        ax_solo.set_xlabel("Sketch Dimension k"); ax_solo.set_ylabel("Top-16 Overlap (%)")
        ax_solo.set_title("Attention Rank Preservation"); ax_solo.set_xscale("log", base=2)
        ax_solo.xaxis.set_major_formatter(mticker.ScalarFormatter())
        ax_solo.set_ylim([0, 108]); ax_solo.set_xticks(sk_dims); ax_solo.grid(True, linestyle="--")
    elif i == 2:
        ax_solo.plot(overheads, [v * 100 for v in top16], "D-", color=ACCENT_BLUE, **marker_kw)
        for x, y, k in zip(overheads, [v * 100 for v in top16], sk_dims):
            ax_solo.annotate(f"k={k}", (x, y), textcoords="offset points",
                             xytext=(8, 4), ha="left", fontsize=9, color=ACCENT_BLUE)
        ax_solo.set_xlabel("Memory Overhead (%)"); ax_solo.set_ylabel("Top-16 Overlap (%)")
        ax_solo.set_title("Quality vs Memory Tradeoff"); ax_solo.set_ylim([0, 108])
        ax_solo.grid(True, linestyle="--")

    ax_solo.tick_color = TEXT
    solo_path = f"results/qjl_{name}.png"
    fig_solo.savefig(solo_path, dpi=150, bbox_inches="tight", facecolor=BG)
    print(f"\u2713 Saved: {solo_path}")
    plt.close(fig_solo)

plt.close(fig)
print(f"\nAll plots saved to results/")
